/* eslint-disable @typescript-eslint/naming-convention */
import Head from 'next/head';
import { Text } from '../../atoms';
import { Card, EventCard } from '../../molecules';
import { KitCardsWrapper, Slider } from '../../organisims';
import styles from './Home.module.scss';
import { IHomeProps } from './Interface';

const Home = (props: IHomeProps) => (
  // There should be no logic codes be placed in this Component, its only use is for presentation
  <div className={styles.wrapper}>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Text size={28} fontWeight={'font-bold'}>
        Home
      </Text>
      <div className={styles.homeHeaderSection}>
        <EventCard />
        <Slider items={props.slider} />
      </div>
      <div className={styles.homeCardWrapper}>
        <Card
          bgColor="default"
          variant="event"
          data={props.cards.homeCardEvent}
        />
        <Card
          bgColor="default"
          variant="builder"
          data={props.cards.homeCardBuilder}
        />
      </div>
      {props.data.map((item, index) => (
        <KitCardsWrapper
          data={item.data.data}
          title={item.title}
          key={index}
          isWrap
          type="buildings"
        />
      ))}
    </main>
  </div>
);
export default Home;
